version: "3"
services:
  server:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports: ["5000:5000"]
    volumes:
      - ../server:/app/server
  client:
    image: nginx:alpine
    ports: ["8080:80"]
    volumes:
      - ../client:/usr/share/nginx/html
