services:
  server:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    working_dir: /app/server
    command: python server.py
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_ENV=production
    volumes:
      - ../server/logs:/app/server/logs   # giữ log ra ngoài container
    restart: unless-stopped
